apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp-chart.fullname" . }}-config
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"