{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "webapp-chart.fullname" . }}
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "webapp-chart.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode }}
  resourcePolicy:
    containerPolicies:
    {{- range .Values.verticalPodAutoscaler.resourcePolicy.containerPolicies }}
    - containerName: {{ .containerName }}
      minAllowed:
        cpu: {{ .minAllowed.cpu }}
        memory: {{ .minAllowed.memory }}
      maxAllowed:
        cpu: {{ .maxAllowed.cpu }}
        memory: {{ .maxAllowed.memory }}
      # Настройка контроллера для оптимизации ресурсов
      # Учитываем, что приложению требуется больше CPU при старте,
      # но в дальнейшем потребление стабилизируется на уровне 0.1 CPU
      controlledResources: ["cpu", "memory"]
      # Настройка для более агрессивного снижения запрашиваемых ресурсов CPU после стабилизации
      mode: Auto
    {{- end }}
{{- end }}